import type {
  CouplingReport,
  CoverageJoinedReport,
  HotspotReport,
  ImpactReport,
  Issue,
  PrDiffReport,
  ReviewReport,
} from '../types.js';
import { calculateScore, badgeMarkdown } from '../utils/scoreCalculator.js';

/**
 * Standalone HTML report (0.16.0+). Each top-level command has its own
 * renderer; the output is a single self-contained HTML document with
 * inline CSS, no external assets, no JS framework. Suitable for posting
 * as a CI artifact or sharing in a PR comment.
 *
 * Style choices:
 *   - System font stack to render readably without webfonts.
 *   - Two-tone colour palette (neutral grey + one accent per severity).
 *   - Tables for data, no charts. Charts would need JS.
 *   - Accessibility: tables get `<th>`s with scope, severity has both
 *     colour AND a text glyph so colourblind readers don't lose info.
 */

const STYLE = `
:root {
  color-scheme: light dark;
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 0;
  padding: 2rem;
  max-width: 1100px;
  margin-inline: auto;
  line-height: 1.5;
  color: #222;
  background: #fafafa;
}
@media (prefers-color-scheme: dark) {
  body { color: #ddd; background: #181818; }
  .card { background: #222; border-color: #333; }
  table { background: #222; }
  th { background: #2a2a2a; }
  tr:nth-child(even) td { background: #1f1f1f; }
  code { background: #2a2a2a; }
  a { color: #6cb6ff; }
}
h1 { margin-top: 0; font-size: 1.6rem; }
h2 { margin-top: 2rem; font-size: 1.2rem; border-bottom: 1px solid #ccc; padding-bottom: 0.3rem; }
.card {
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 1rem 1.2rem;
  margin-bottom: 1rem;
}
.score { font-size: 2.5rem; font-weight: 700; }
.grade-A, .grade-A\\+ { color: #1a8a4a; }
.grade-B { color: #4a8a1a; }
.grade-C { color: #c79100; }
.grade-D { color: #d6582d; }
.grade-F { color: #d63333; }
table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; background: #fff; }
th, td { padding: 0.4rem 0.6rem; text-align: left; border-bottom: 1px solid #eee; }
th { background: #f3f3f3; font-weight: 600; }
tr:nth-child(even) td { background: #f9f9f9; }
code { background: #f0f0f0; padding: 0.05em 0.4em; border-radius: 3px; font-size: 0.95em; }
.severity-error { color: #d63333; }
.severity-warning { color: #c79100; }
.severity-info { color: #4a6a8a; }
.muted { color: #888; font-size: 0.9rem; }
.verdict-ok { color: #1a8a4a; font-weight: 700; }
.verdict-review { color: #c79100; font-weight: 700; }
.verdict-block { color: #d63333; font-weight: 700; }
.right { text-align: right; }
.tag { display: inline-block; padding: 0.05em 0.5em; border-radius: 3px; background: #e8e8e8; font-size: 0.85em; }
.tag-new { background: #ffd6d6; color: #8a0000; }
.tag-expanded { background: #fff3c4; color: #6a4a00; }
`.trim();

/** Wrap inner HTML in a complete document. Title is required for accessibility. */
export function htmlShell(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>${STYLE}</style>
</head>
<body>
${bodyHtml}
<footer class="muted" style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ccc;">
Generated by <a href="https://github.com/abhiyoheswaran1/projscan">projscan</a> at ${new Date().toISOString()}
</footer>
</body>
</html>`;
}

export function reportHealthHtml(issues: Issue[]): void {
  const { score, grade, errors, warnings, infos } = calculateScore(issues);
  const sevTotals = `<span class="severity-error">${errors}</span> errors · <span class="severity-warning">${warnings}</span> warnings · <span class="severity-info">${infos}</span> info`;
  const issuesHtml =
    issues.length === 0
      ? '<p>No issues detected. Project looks healthy.</p>'
      : `<table>
<thead><tr><th>Severity</th><th>Title</th><th>Description</th><th>Suggested action</th></tr></thead>
<tbody>${issues
          .map(
            (i) =>
              `<tr>
<td class="severity-${i.severity}">${severityIcon(i.severity)} ${i.severity}</td>
<td><code>${escapeHtml(i.id)}</code><br>${escapeHtml(i.title)}</td>
<td class="muted">${escapeHtml(i.description)}</td>
<td>${i.suggestedAction ? `${escapeHtml(i.suggestedAction.summary)}<br><code>projscan fix-suggest ${escapeHtml(i.id)}</code>` : '<span class="muted">—</span>'}</td>
</tr>`,
          )
          .join('\n')}</tbody>
</table>`;

  const body = `
<h1>Project health</h1>
<div class="card">
<div class="score grade-${grade.replace('+', '\\+')}">${grade}</div>
<div>${score} / 100 — ${sevTotals}</div>
<p class="muted" style="margin-bottom: 0;">${badgeMarkdown(grade)}</p>
</div>
<h2>Issues (${issues.length})</h2>
${issuesHtml}
`;
  console.log(htmlShell(`Health · ${grade} (${score}/100)`, body));
}

export function reportHotspotsHtml(report: HotspotReport): void {
  if (!report.available) {
    console.log(
      htmlShell(
        'Hotspots — unavailable',
        `<h1>Hotspots</h1><p class="muted">${escapeHtml(report.reason ?? 'Hotspots unavailable.')}</p>`,
      ),
    );
    return;
  }
  const rows = report.hotspots
    .map(
      (h, i) =>
        `<tr>
<td class="right">${i + 1}</td>
<td class="right">${h.riskScore.toFixed(1)}</td>
<td><code>${escapeHtml(h.relativePath)}</code></td>
<td class="right">${h.churn}</td>
<td class="right">${typeof h.cyclomaticComplexity === 'number' ? h.cyclomaticComplexity : '-'}</td>
<td class="right">${h.lineCount}</td>
<td class="right">${h.issueCount}</td>
<td class="muted">${escapeHtml(h.reasons.join(', '))}</td>
</tr>`,
    )
    .join('\n');
  const body = `
<h1>Hotspots</h1>
<p class="muted">Window: <strong>${escapeHtml(String(report.window.since ?? 'all'))}</strong> · ${report.window.commitsScanned} commit(s) scanned · ${report.totalFilesRanked} file(s) ranked</p>
<table>
<thead><tr><th>#</th><th class="right">Score</th><th>File</th><th class="right">Churn</th><th class="right">CC</th><th class="right">Lines</th><th class="right">Issues</th><th>Reasons</th></tr></thead>
<tbody>${rows}</tbody>
</table>
`;
  console.log(htmlShell('Hotspots', body));
}

export function reportCouplingHtml(report: CouplingReport): void {
  const cyclesHtml =
    report.cycles.length === 0
      ? '<p class="muted">No circular imports detected.</p>'
      : `<table>
<thead><tr><th class="right">Size</th><th>Files</th></tr></thead>
<tbody>${report.cycles
          .map(
            (c) =>
              `<tr><td class="right">${c.size}</td><td>${c.files.map((f) => `<code>${escapeHtml(f)}</code>`).join(' → ')}</td></tr>`,
          )
          .join('\n')}</tbody>
</table>`;

  const filesRows = report.files
    .slice(0, 100)
    .map(
      (f) =>
        `<tr><td><code>${escapeHtml(f.relativePath)}</code></td><td class="right">${f.fanIn}</td><td class="right">${f.fanOut}</td><td class="right">${f.instability.toFixed(3)}</td></tr>`,
    )
    .join('\n');

  const body = `
<h1>Coupling</h1>
<h2>Cycles (${report.cycles.length})</h2>
${cyclesHtml}
<h2>Files (top 100 by fan-in)</h2>
<table>
<thead><tr><th>File</th><th class="right">Fan-in</th><th class="right">Fan-out</th><th class="right">Instability</th></tr></thead>
<tbody>${filesRows}</tbody>
</table>
`;
  console.log(htmlShell('Coupling', body));
}

export function reportReviewHtml(report: ReviewReport): void {
  if (!report.available) {
    console.log(
      htmlShell(
        'PR Review — unavailable',
        `<h1>PR Review</h1><p class="muted">${escapeHtml(report.reason ?? 'Review unavailable.')}</p>`,
      ),
    );
    return;
  }
  const verdictClass = `verdict-${report.verdict}`;
  const verdictLabel =
    report.verdict === 'block' ? '🚫 BLOCK' : report.verdict === 'review' ? '👀 REVIEW' : '✅ OK';

  const filesHtml =
    report.changedFiles.length === 0
      ? '<p class="muted">No structural changes.</p>'
      : `<table>
<thead><tr><th>File</th><th>Status</th><th class="right">Risk</th><th class="right">CC</th><th class="right">ΔCC</th></tr></thead>
<tbody>${report.changedFiles
          .slice(0, 100)
          .map(
            (f) =>
              `<tr>
<td><code>${escapeHtml(f.relativePath)}</code></td>
<td class="muted">${f.status}</td>
<td class="right">${f.riskScore !== null ? f.riskScore.toFixed(1) : '-'}</td>
<td class="right">${f.cyclomaticComplexity ?? '-'}</td>
<td class="right">${f.cyclomaticDelta === null ? '-' : signed(f.cyclomaticDelta)}</td>
</tr>`,
          )
          .join('\n')}</tbody>
</table>`;

  const cyclesHtml =
    report.newCycles.length === 0
      ? ''
      : `<h2>New / expanded cycles</h2>
<ul>${report.newCycles
          .map(
            (c) =>
              `<li><span class="tag tag-${c.classification}">${c.classification}</span> (${c.size} files): ${c.files.map((f) => `<code>${escapeHtml(f)}</code>`).join(' → ')}</li>`,
          )
          .join('\n')}</ul>`;

  const fnsHtml =
    report.riskyFunctions.length === 0
      ? ''
      : `<h2>Risky functions</h2>
<table>
<thead><tr><th>Function</th><th>File</th><th class="right">CC</th><th>Reason</th><th>Δ</th></tr></thead>
<tbody>${report.riskyFunctions
          .slice(0, 50)
          .map(
            (fn) =>
              `<tr>
<td><code>${escapeHtml(fn.name)}</code></td>
<td><code>${escapeHtml(fn.file)}</code>:L${fn.line}</td>
<td class="right">${fn.cyclomaticComplexity}</td>
<td class="muted">${fn.reason}</td>
<td>${fn.baseCc === null ? 'new' : `${fn.baseCc} → ${fn.cyclomaticComplexity}`}</td>
</tr>`,
          )
          .join('\n')}</tbody>
</table>`;

  const depsHtml =
    report.dependencyChanges.length === 0
      ? ''
      : `<h2>Dependency changes</h2>${report.dependencyChanges
          .map(
            (d) => `
<h3>${escapeHtml(d.manifestFile)}${d.workspace ? ` <span class="muted">(${escapeHtml(d.workspace)})</span>` : ''}</h3>
<ul>
${d.added.map((a) => `<li>➕ <code>${escapeHtml(a.name)}@${escapeHtml(a.version)}</code> <span class="muted">(${a.kind})</span></li>`).join('\n')}
${d.removed.map((r) => `<li>➖ <code>${escapeHtml(r.name)}@${escapeHtml(r.version)}</code> <span class="muted">(${r.kind})</span></li>`).join('\n')}
${d.bumped.map((b) => `<li>🔄 <code>${escapeHtml(b.name)}</code>: ${escapeHtml(b.from)} → ${escapeHtml(b.to)} <span class="muted">(${b.kind})</span></li>`).join('\n')}
</ul>`,
          )
          .join('\n')}`;

  const body = `
<h1>PR Review</h1>
<div class="card">
<p class="muted">base <code>${escapeHtml(report.base.ref)}</code> (${report.base.resolvedSha?.slice(0, 7) ?? '?'}) → head <code>${escapeHtml(report.head.ref)}</code> (${report.head.resolvedSha?.slice(0, 7) ?? '?'})</p>
<p class="${verdictClass}" style="font-size: 1.4rem; margin: 0.5rem 0;">${verdictLabel}</p>
<ul>${report.summary.map((s) => `<li>${escapeHtml(s)}</li>`).join('\n')}</ul>
</div>
<h2>Changed files</h2>
${filesHtml}
${cyclesHtml}
${fnsHtml}
${depsHtml}
`;
  console.log(htmlShell(`PR Review (${verdictLabel.replace(/[^A-Za-z]/g, '').trim()})`, body));
}

export function reportPrDiffHtml(report: PrDiffReport): void {
  if (!report.available) {
    console.log(
      htmlShell(
        'PR Diff — unavailable',
        `<h1>PR Structural Diff</h1><p class="muted">${escapeHtml(report.reason ?? 'PR diff unavailable.')}</p>`,
      ),
    );
    return;
  }

  const addedHtml =
    report.filesAdded.length === 0
      ? ''
      : `<h2>Added (${report.filesAdded.length})</h2>
<ul>${report.filesAdded.map((f) => `<li><code>${escapeHtml(f)}</code></li>`).join('\n')}</ul>`;

  const removedHtml =
    report.filesRemoved.length === 0
      ? ''
      : `<h2>Removed (${report.filesRemoved.length})</h2>
<ul>${report.filesRemoved.map((f) => `<li><code>${escapeHtml(f)}</code></li>`).join('\n')}</ul>`;

  const modifiedHtml =
    report.filesModified.length === 0
      ? ''
      : `<h2>Modified (${report.filesModified.length})</h2>
${report.filesModified
  .slice(0, 100)
  .map((m) => {
    const dCC = m.cyclomaticDelta === null ? '' : ` · ΔCC ${signed(m.cyclomaticDelta)}`;
    const dFI =
      m.fanInDelta === null || m.fanInDelta === 0 ? '' : ` · Δfan-in ${signed(m.fanInDelta)}`;
    const lines: string[] = [];
    if (m.exportsAdded.length > 0)
      lines.push(
        `<li><strong class="severity-info">+exports:</strong> ${m.exportsAdded.map((s) => `<code>${escapeHtml(s)}</code>`).join(', ')}</li>`,
      );
    if (m.exportsRemoved.length > 0)
      lines.push(
        `<li><strong class="severity-error">−exports:</strong> ${m.exportsRemoved.map((s) => `<code>${escapeHtml(s)}</code>`).join(', ')}</li>`,
      );
    if (m.exportsRenamed.length > 0) {
      const pairs = m.exportsRenamed
        .map((r) => `<code>${escapeHtml(r.from)}</code> → <code>${escapeHtml(r.to)}</code>`)
        .join(', ');
      lines.push(`<li><strong class="severity-warning">~exports:</strong> ${pairs}</li>`);
    }
    if (m.importsAdded.length > 0)
      lines.push(
        `<li><strong class="severity-info">+imports:</strong> ${m.importsAdded.map((s) => `<code>${escapeHtml(s)}</code>`).join(', ')}</li>`,
      );
    if (m.importsRemoved.length > 0)
      lines.push(
        `<li><strong class="severity-error">−imports:</strong> ${m.importsRemoved.map((s) => `<code>${escapeHtml(s)}</code>`).join(', ')}</li>`,
      );
    const inner =
      lines.length === 0
        ? '<p class="muted">No structural change beyond CC / fan-in.</p>'
        : `<ul>${lines.join('\n')}</ul>`;
    return `<h3><code>${escapeHtml(m.relativePath)}</code><span class="muted">${dCC}${dFI}</span></h3>\n${inner}`;
  })
  .join('\n')}
${report.filesModified.length > 100 ? `<p class="muted">… and ${report.filesModified.length - 100} more</p>` : ''}`;

  const body = `
<h1>PR Structural Diff</h1>
<p class="muted">base <code>${escapeHtml(report.base.ref)}</code> (${report.base.resolvedSha?.slice(0, 7) ?? '?'}) → head <code>${escapeHtml(report.head.ref)}</code> (${report.head.resolvedSha?.slice(0, 7) ?? '?'})</p>
<p><strong>${report.totalFilesChanged}</strong> file(s) changed: <span class="severity-info">+${report.filesAdded.length}</span> added, <span class="severity-error">−${report.filesRemoved.length}</span> removed, <span class="severity-warning">~${report.filesModified.length}</span> modified.</p>
${addedHtml}
${removedHtml}
${modifiedHtml}
`;
  console.log(htmlShell('PR Structural Diff', body));
}

export function reportCoverageHtml(report: CoverageJoinedReport): void {
  if (!report.available) {
    console.log(
      htmlShell(
        'Coverage — unavailable',
        `<h1>Coverage × Risk</h1><p class="muted">${escapeHtml(report.reason ?? 'Coverage unavailable.')}</p>`,
      ),
    );
    return;
  }
  const rows = report.entries
    .slice(0, 100)
    .map((h, i) => {
      const cov = h.coverage;
      const covPct = cov === null ? '-' : `${Math.round(cov * 100)}%`;
      const danger = cov !== null && cov < 0.5 && h.riskScore > 50;
      const cls = danger ? ' class="severity-error"' : '';
      return `<tr${cls}>
<td class="right">${i + 1}</td>
<td><code>${escapeHtml(h.relativePath)}</code></td>
<td class="right">${h.riskScore.toFixed(1)}</td>
<td class="right">${covPct}</td>
<td class="right">${h.priority.toFixed(1)}</td>
<td class="right">${h.lineCount}</td>
<td class="muted">${escapeHtml(h.reasons.join(', '))}</td>
</tr>`;
    })
    .join('\n');
  const sourceLabel = report.coverageSource ?? 'no coverage source';
  const sourceFile = report.coverageSourceFile
    ? ` (<code>${escapeHtml(report.coverageSourceFile)}</code>)`
    : '';
  const body = `
<h1>Coverage × Risk</h1>
<p class="muted">Source: ${escapeHtml(sourceLabel)}${sourceFile} · ${report.entries.length} file(s) ranked.</p>
<p>Rows highlighted in red have <strong>coverage &lt; 50%</strong> AND <strong>risk score &gt; 50</strong> — the "scariest untested files" combination. The Priority column blends risk and uncovered fraction; rows are sorted by it.</p>
<table>
<thead><tr><th>#</th><th>File</th><th class="right">Risk</th><th class="right">Coverage</th><th class="right">Priority</th><th class="right">Lines</th><th>Reasons</th></tr></thead>
<tbody>${rows}</tbody>
</table>
${report.entries.length > 100 ? `<p class="muted">… and ${report.entries.length - 100} more</p>` : ''}
`;
  console.log(htmlShell('Coverage × Risk', body));
}

export function reportImpactHtml(report: ImpactReport): void {
  if (!report.available) {
    console.log(
      htmlShell(
        'Impact — unavailable',
        `<h1>Impact</h1><p class="muted">${escapeHtml(report.reason ?? 'Impact unavailable.')}</p>`,
      ),
    );
    return;
  }
  const defs =
    report.definitionFiles.length === 0
      ? ''
      : `<h2>Defined in</h2><ul>${report.definitionFiles.map((f) => `<li><code>${escapeHtml(f)}</code></li>`).join('\n')}</ul>`;

  const reachable =
    report.reachable.length === 0
      ? '<p class="muted">No reachable files.</p>'
      : `<table>
<thead><tr><th class="right">Distance</th><th>File</th></tr></thead>
<tbody>${report.reachable
          .slice(0, 200)
          .map(
            (n) =>
              `<tr><td class="right">${n.distance}</td><td><code>${escapeHtml(n.file)}</code></td></tr>`,
          )
          .join('\n')}</tbody>
</table>`;

  const body = `
<h1>Impact: ${escapeHtml(report.target.kind)} <code>${escapeHtml(report.target.value)}</code></h1>
<p class="muted">${report.totalReachable} file(s) reachable within distance ${report.maxDistance}${report.truncated ? ' (truncated; more files exist beyond)' : ''}.</p>
${defs}
<h2>Reachable</h2>
${reachable}
`;
  console.log(htmlShell(`Impact: ${report.target.value}`, body));
}

// ── helpers ───────────────────────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function severityIcon(s: 'info' | 'warning' | 'error'): string {
  switch (s) {
    case 'error':
      return '✕';
    case 'warning':
      return '!';
    default:
      return 'i';
  }
}

function signed(n: number): string {
  return n >= 0 ? `+${n}` : String(n);
}
